name: Fresh AOSP Build on EC2 with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup_aosp:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Set EC2 Instance Details
        run: |
          echo "INSTANCE_ID=i-0c095a956111f7bb1" >> $GITHUB_ENV
          echo "INSTANCE_IP=13.48.47.239" >> $GITHUB_ENV

      - name: Setup SSH Key for EC2 Access
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          
      - name: Configure Swap Space (64GB)
        run: |
          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << "EOF"
            sudo fallocate -l 64G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            echo '/swapfile swap swap defaults 0 0' | sudo tee -a /etc/fstab
            sudo sysctl vm.swappiness=10
            echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf
          EOF

      - name: Install Docker on EC2
        run: |
          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << "EOF"
            sudo apt update && sudo apt install -y docker.io
            sudo usermod -aG docker ubuntu
            sudo systemctl restart docker
          EOF

      - name: Check and Use Prebuilt Docker Image
        run: |
          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text) << EOF
            IMAGE_EXISTS=\$(docker pull doredlap/aosp-builder:1.3 2>&1 | grep 'not found')
            if [[ -z "\$IMAGE_EXISTS" ]]; then
              echo "Docker image found, running container..."
              docker run -d --name aosp-container --restart unless-stopped -v /home/ubuntu/aosp:/workspace doredlap/aosp-builder:1.3
            else
              echo "Docker image not found, building and pushing..."
              mkdir -p /home/ubuntu/aosp && cd /home/ubuntu/aosp
              
              echo "FROM ubuntu:20.04" > Dockerfile
              echo "ENV DEBIAN_FRONTEND=noninteractive" >> Dockerfile
              echo "RUN apt update && apt install -y git curl python3 python3-pip openjdk-11-jdk wget unzip gcc g++ make libncurses5 libncurses5-dev bison flex gperf zip zlib1g-dev ccache lzop lsb-release sudo python-is-python3" >> Dockerfile
              
              # Ensure timezone configuration runs before installing tzdata
              echo "RUN ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime" >> Dockerfile
              echo "RUN echo 'Asia/Kolkata' > /etc/timezone" >> Dockerfile
              echo "RUN apt update && apt install -y tzdata" >> Dockerfile
              echo "RUN dpkg-reconfigure --frontend noninteractive tzdata" >> Dockerfile
              
              # Install repo and setup environment
              echo "RUN mkdir -p /usr/local/bin && curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo" >> Dockerfile
              echo "RUN chmod a+x /usr/local/bin/repo && ln -s /usr/local/bin/repo /usr/bin/repo" >> Dockerfile
              
              echo "WORKDIR /workspace" >> Dockerfile
              echo "COPY entrypoint.sh /entrypoint.sh" >> Dockerfile
              echo "RUN chmod +x /entrypoint.sh" >> Dockerfile
              echo "ENTRYPOINT [\"/entrypoint.sh\"]" >> Dockerfile
              
              echo "#!/bin/bash" > entrypoint.sh
              echo "exec tail -f /dev/null" >> entrypoint.sh
              chmod +x entrypoint.sh

              
              echo "Building Docker image..."
              docker build -t doredlap/aosp-builder:1.3 .
              echo "Pushing Docker image to Docker Hub..."
              echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username doredlap --password-stdin
              docker push doredlap/aosp-builder:1.3
              docker run -d --name aosp-container --restart unless-stopped -v /home/ubuntu/aosp:/workspace doredlap/aosp-builder:1.3

            fi
          EOF
      - name: Execute Repo Commands in Container
        run: |
          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << "EOF"
            echo "Executing repo commands inside container..."
           docker exec aosp-container bash -c "
            repo init -u https://android.googlesource.com/platform/manifest
            repo sync -c -j$(nproc)
          "
          EOF

      - name: Set Up Environment & Build AOSP
        run: |
          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << "EOF"
            docker exec aosp-container bash -c "
              if [ ! -d /workspace/.repo ]; then
                echo 'Error: Repo sync may have failed. .repo directory not found.'
                exit 1
              fi

              if [ -f build/envsetup.sh ]; then
                source build/envsetup.sh
                lunch aosp_cf_x86_64_tv-userdebug
                make -j\$(nproc) 2>&1 | tee /workspace/logs/build.log
              else
                echo 'Error: build/envsetup.sh not found!'
                exit 1
              fi
            "
          EOF

