name: Run Workflow on Existing EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute_on_ec2:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Setup SSH Key for EC2 Access
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      - name: Install AWS CLI on EC2 Using Official Installer
        run: |
          ssh -o StrictHostKeyChecking=no -i private-key.pem ubuntu@51.20.79.81 "
            curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip' &&
            unzip awscliv2.zip &&
            sudo ./aws/install &&
            aws --version
          "

      - name: Run Commands on Existing EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private-key.pem ubuntu@51.20.79.81 << 'EOF'
          echo "Running on EC2 instance: i-0b372ce164da60a78"
          echo 'Hello, world!' > helloworld.txt
          aws s3 cp helloworld.txt s3://piplineflow/
          EOF
